# Use Travis CI's container infrastructure to enable caching.
sudo: false

# "haskell" will set up the whole haskell-platform.  We don't need that.
language: c

addons:
  apt:
    packages:
    - libgmp-dev

env:
  - ARGS=""
  - ARGS="--resolver lts-2"
  - ARGS="--resolver lts-3"
  - ARGS="--resolver lts"
  - ARGS="--resolver nightly"

before_install:
  - mkdir -p $HOME/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.5.0/stack-0.1.5.0-x86_64-linux.tar.gz | tar xz --strip-components=1 -C ~/.local/bin

install:
  - stack $ARGS --no-terminal --install-ghc build
  
script:
  - stack $ARGS --no-terminal test

# Speed up subsequent builds using Stack caching.  
cache:
  directories:
    - $HOME/.stack
